
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Get environment variables with fallbacks
// For production, set these in your hosting platform's environment variables
// For local development, you can create a .env file with these values
const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
  console.warn(
    'Supabase URL or key not found in environment variables. ' +
    'Please set VITE_SUPABASE_URL and VITE_SUPABASE_PUBLISHABLE_KEY in your environment.'
  );
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL || 'https://ahwdtfgtmjtpiomcwncn.supabase.co', 
  SUPABASE_PUBLISHABLE_KEY || 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFod2R0Zmd0bWp0cGlvbWN3bmNuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM0NTA3NzQsImV4cCI6MjA1OTAyNjc3NH0.sHqNwwXZ9ir3AVsmxTmmGNB0eaTPBwzIqJiCB1qfWtU',
  {
    auth: {
      persistSession: true,
      autoRefreshToken: true,
    }
  }
);
